module.exports = {
    env: {
        SERVER: process.env.SERVER,
        MEDIA_SERVER: process.env.MEDIA_SERVER,
        NEXTAUTH_URL: process.env.SERVER,
        FTP_HOST: process.env.FTP_HOST,
        FTP_PORT: process.env.FTP_PORT,
        FTP_TLS: process.env.FTP_TLS,
        FTP_USER: process.env.FTP_USER,
        FTP_PASS: process.env.FTP_PASS,
        FTP_BASEDIR: process.env.FTP_BASEDIR,
        DB_NAME: process.env.DB_NAME,
        DB_HOST: process.env.DB_HOST,
        DB_USER: process.env.DB_USER,
        DB_PASS: process.env.DB_PASS,
        DB_URL: `mysql://${process.env.DB_USER}:${process.env.DB_PASS}@${process.env.DB_HOST}/${process.env.DB_NAME}?schema=public`,
        SECRET: process.env.SECRET,
        GOOGLE_ID: process.env.GOOGLE_ID,
        GOOGLE_SECRET: process.env.GOOGLE_SECRET,
        LOCALE: process.env.LOCALE,
    },
    images: {
        domains: [process.env.MEDIA_SERVER.replace('https://', '').replace('http://', '')],
    },
    i18n: {
        locales: ['en', 'fr'],
        defaultLocale: process.env.LOCALE,
        localeDetection: true,
    },
};
